language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake . && make unit_test && ./unit_test

matrix:
  include:
    - os: linux
      env:
         - MATRIX_EVAL="COMPILER_NAME=clang && CC=clang CXX=clang++"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="COMPILER_NAME=gcc-4.9 && CC=gcc-4.9 CXX=g++-4.9"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="COMPILER_NAME=gcc-5 && CC=gcc-5 CXX=g++-5"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="COMPILER_NAME=gcc-6 && CC=gcc-6 CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="COMPILER_NAME=gcc-7 && CC=gcc-7 CXX=g++-7"