language: generic
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
script:
  - cmake . && make unit_test && ./unit_test
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      env:
         - COMPILER_NAME=clang
         - CC=clang
         - CXX=clang++
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - COMPILER_NAME=gcc-4.9
         - CC=gcc-4.9
         - CXX=g++-4.9

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - COMPILER_NAME=gcc-5
         - CC=gcc-5
         - CXX=g++-5

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
         - COMPILER_NAME=gcc-6
         - CC=gcc-6
         - CXX=g++-6

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
         - COMPILER_NAME=gcc-7
         - CC=gcc-7
         - CXX=g++-7

#before_install:
#    - eval "${MATRIX_EVAL}"