language: cpp
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake
      - valgrind

before_install:
    - eval "${MATRIX_EVAL}"

script:
  - cmake . && make unit_test && valgrind --leak-check=full --track-origins=yes ./unit_test

matrix:
  include:
    - os: linux
      env:
         - MATRIX_EVAL="COMPILER_NAME=clang && CC=clang CXX=clang++"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake-data
            - cmake
            - valgrind
      env:
        - MATRIX_EVAL="COMPILER_NAME=gcc-6 && CC=gcc-6 CXX=g++-6"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake-data
            - cmake
            - valgrind
      env:
        - MATRIX_EVAL="COMPILER_NAME=gcc-7 && CC=gcc-7 CXX=g++-7"