FROM docker.io/library/golang:1.20-bullseye as builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . ./

RUN cd terraform/
RUN go generate

RUN go build -o terraform-provider-protomesh .

