enable.controller = true
enable.proxy = true
enable.server = true

[log]

dev = true
json = false
level = "debug"

[aws]

enable.grpc.lambda.router = true
dynamodb.endpoint.url = ""

[grpc]

server.enable.reflection = true

[http]

server.shutdown.timeout.duration = "2m"

[http.server.tls]

# certificate.certificates.path = ""
# certificate.private.key.path = ""
# insecure.skip.verify = true
# root.cas.path = ""

listener.address = "0.0.0.0:7227"
protocol = "tcp"

[temporal]

address = "127.0.0.1:7223"
namespace = "default"

[controller]

controls.worker.task.queue = "graviflow"

[controller.resource.store]

client.certificate.path = ""
client.enable.tls = false
server.address = "127.0.0.1:7227"

[proxy]

grpc.router = "AwsLambda"

[proxy.edge]

resource.store.namespace = "proxy"
sync.interval = "1m"

[proxy.resource.store]

client.certificate.path = ""
client.enable.tls = false
server.address = "127.0.0.1:7227"

[server]

server.resource.store.provider = "AwsDynamoDB"

[server.resource.store]

client.certificate.path = ""
client.enable.tls = false
server.address = "127.0.0.1:7227"

[server.dynamodb]

resource.namespace.secondary.index = "namespace_idx"
resource.table.name = "graviflow_resources"

[server.envoy.xds]

enable = true
resource.store.namespace = "envoy"
sync.interval = "1m"