enable.server = true

enable.controller = false
enable.proxy = false

[log]

dev = true
json = false
level = "debug"

[aws]

dynamodb.endpoint.url = "http://dynamodb:8000"

[grpc]

server.enable.reflection = true

[http]

server.shutdown.timeout.duration = "2m"

[http.server.tls]

# certificate.certificates.path = ""
# certificate.private.key.path = ""
# insecure.skip.verify = true
# root.cas.path = ""

listener.address = "0.0.0.0:6680"
protocol = "tcp"

[server.resource.store]

provider = "Postgres"

client.certificate.path = ""
client.enable.tls = true
server.address = "127.0.0.1:6680"

[server.sql]

driver.name = "postgres"
connection.string = "host=postgresql port=5432 user=protomesh password=protomesh dbname=protomesh sslmode=disable"

[server.postgres]

migration.file = "/var/protomesh/postgres/schema"

[server.envoy.xds]

enable = true
resource.store.namespace = "envoy"
sync.interval = "1m"