enable.worker = true

enable.proxy = false
enable.server = false

[log]

dev = true
json = false
level = "debug"

[temporal]

address = "temporal:7233"
namespace = "default"

[worker.service]

resource.store.namespace = "workflows"
sync.interval = "1m"
worker.task.queue = "protomesh"

[worker.resource.store]

client.certificate.path = ""
client.enable.tls = true
server.address = "store:6680"
